dataset: hanchuan
raw_dir: data/raw/hanchuan
cube_file: WHU_Hi_HanChuan.mat
gt_file: WHU_Hi_HanChuan_gt.mat
cube_key: ''
gt_key: ''
label_offset: 1
name: hanchuan
processed_dir: data/processed/hanchuan/raw
num_classes: 16
