dataset: honghu
raw_dir: data/raw/honghu
cube_file: WHU_Hi_HongHu.mat
gt_file: WHU_Hi_HongHu_gt.mat
cube_key: ''
gt_key: ''
label_offset: 1
name: honghu
processed_dir: data/processed/honghu/raw
num_classes: 22
