dataset: houston2013
raw_dir: data/raw/houston2013
cube_file: Houston.mat
gt_file: Houston_gt.mat
cube_key: ''
gt_key: ''
label_offset: 1
name: houston2013
processed_dir: data/processed/houston2013/raw
num_classes: 15
