dataset: pavia_university
raw_dir: data/raw/pavia_university
cube_file: PaviaU.mat
gt_file: PaviaU_gt.mat
cube_key: ''
gt_key: ''
label_offset: 1
name: pavia_university
processed_dir: data/processed/pavia_university/raw
num_classes: 9
